name: Test & Deploy
on:
  push:
    branches:
      - main

jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo and checkout main
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Run test-utils
        run: npm run test-utils

  test-app: 
    runs-on: ubuntu-latest
    needs: test-utils
    steps: 
      - name: Clone repo and checkout main
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Setup of PSQL
        uses: harmon758/postgresql-action@v1
        with: 
          postgresql db: test_database
          postgresql user: elenatropanets
          postgresql password: password
      - name: Run test-app
        run: PGDATABASE=test_database PGPASSWORD=password PGUSER=elenatropanets npm run test-app